### ISSUE TITLE
Error when importing fixtures

### ISSUE THREAD

**Issue by KevinHock** [Yelp/fuzz-lightyear#26]
https://github.com/Yelp/fuzz-lightyear/blob/19c3c57d0d5a005bee52d362f552e9fdaba26767/fuzz_lightyear/discovery.py#L29

doesn't do what we thought it did, e.g. the module name endswith `p` or `y`, you'll strip that too.

https://developmentality.wordpress.com/2018/03/12/rstripping-simon-pegg-dont-use-rstrip-for-file-extension-removal/

**Comment by domanchi** [comment]
Yay! This is done.
