### ISSUE TITLE
Update fuzz-lightyear to be compatible with latest Hypothesis version

### ISSUE THREAD

**Issue by tanx16** [Yelp/fuzz-lightyear#40]
Hypothesis renamed a function that fuzz-lightyear uses, `searchstrategy`, into `strategies.internal`. Let's update fuzz-lightyear to be compatible with that.

See: https://github.com/HypothesisWorks/hypothesis/commit/60e4f52fc03061c8f40d3bc56dd7849a6845b2c5#diff-926393cc3ca9906fbedb7495c16ff672

**Comment by OiCMudkips** [comment]
This is done :)
