### ISSUE TITLE
Error: Invalid swagger format

### ISSUE THREAD

**Issue by holumyn** [Yelp/fuzz-lightyear#47]
After installing, I ran fuzz-lightyear on the sample swagger doc. I received `Error: invalid swager format`. Please advise on what may be wrong.

**Reproduction Step**
`pip install fuzz-lightyear`

`fuzz-lightyear https://petstore.swagger.io/v2/swagger.json -v --ignore-exceptions`

**Error Message**
`Error: Invalid swagger format`
FYI: I tried with addition self hosted swagger(.json) files but the result is the same

fuzz-lightyear 0.0.6
Mac 10.14.6
Python - Ran on 3.7.3 and 3.6.10

**Comment by domanchi** [comment]
Hi @holumyn,

This is bizarre. I've tried installing both HEAD (v0.0.7) and your specified version (v0.0.6), and have not been able to reproduce the error message. Can you provide a traceback?

**Comment by holumyn** [comment]
Hi @domanchi . Thanks for the feedback.

I tried on a windows environment and it works as expected. I will run further trace on my Mac and share my findings.
