### ISSUE TITLE
Does fuzz-lightyear follow “Successful Request Sequences Only” strategy?

### ISSUE THREAD

**Issue by AlexB1986** [Yelp/fuzz-lightyear#56]
Hi Team! Thank you for your efforts and open sourcing such interesting tool!

While playing with Fuzz-lightyear we faced with interesting issue – it seems that fuzz-lightyear does not follow [“Successful Request Sequences Only” strategy](https://github.com/Yelp/fuzz-lightyear/blob/master/CONTRIBUTING.md#successful-request-sequences-only).
Could you please check our results?

**Detailed information**
Let’s consider generating 2-length sequences (we used [Mozilla Kinto](https://docs.kinto-storage.org/en/stable/api/index.html) as a target of testing). Before generating 2-length sequences last_result (based on 1-length sequences validation) is:
![image](https://user-images.githubusercontent.com/22557771/93192851-c9995380-f74e-11ea-954d-bcd69cbfd076.png)
Function _add_request_to_sequence generate a following sequence for validation:
![image](https://user-images.githubusercontent.com/22557771/93192892-d9189c80-f74e-11ea-9962-6c901abfd74e.png)
[Before yield results](https://github.com/Yelp/fuzz-lightyear/blob/master/fuzz_lightyear/generator.py#L80) into validate_sequence result.responses.responses structure is:
![image](https://user-images.githubusercontent.com/22557771/93192966-f188b700-f74e-11ea-9976-b0aeea1e1569.png)
Then we yield sequence into [validate_sequence](https://github.com/Yelp/fuzz-lightyear/blob/master/fuzz_lightyear/main.py#L136)
First request is OK:
![image](https://user-images.githubusercontent.com/22557771/93193033-082f0e00-f74f-11ea-802b-408d45353df9.png)
and we add data to responses.responses:
![image](https://user-images.githubusercontent.com/22557771/93193087-141ad000-f74f-11ea-9c3d-51ccd17c5663.png)
Second request is not OK (404)
![image](https://user-images.githubusercontent.com/22557771/93193174-2e54ae00-f74f-11ea-8911-6d982eb187ac.png)
and we pass to [exception block](https://github.com/Yelp/fuzz-lightyear/blob/master/fuzz_lightyear/main.py#L137) and do not add any data to responses.responses.

When we obtain “result” in [line](https://github.com/Yelp/fuzz-lightyear/blob/master/fuzz_lightyear/generator.py#L82), it looks like:
![image](https://user-images.githubusercontent.com/22557771/93193309-5b08c580-f74f-11ea-914e-42d5bfa5c219.png)

I.e., there are two requests and only one response (because second response was not successful). But result.is_successful() == true and we add that sequence (that is actually not a successful request sequence) to good_sequences and we will use it to construct 3-length sequences later.

To test our assumption we modify is_successful() [implementation](https://github.com/Yelp/fuzz-lightyear/blob/master/fuzz_lightyear/result.py#L21) in the following way

_return bool(self.responses) → return bool(self.responses) and bool(len(self.responses) == len(self.requests))_

and made testing  of two version (original and modified) against a same target ([Mozilla Kinto](https://docs.kinto-storage.org/en/stable/api/index.html)) of testing with one seed and n=3. The results are:

- original version: 1424 failed, 260 passed, in 74.45 seconds
- modified version: 495 failed, 230 passed, in 36.78 seconds

That modification allows us to reduce running time and increase ratio of passed/(passed+falled).

**Comment by domanchi** [comment]
Hi @AlexB1986,

What a great idea to use Mozilla Kinto to test this! And thank you for your detailed bug report. I think you might be on to something -- let me verify on our end, and report back with results.

**Comment by domanchi** [comment]
I was able to reproduce this in a test case. It looks like we do indeed respect "Successful Request Sequences Only" (that is, a failed request will quit the sequence early), however, due to the bug you correctly identified, a failed sequence isn't accurately reflected in `FuzzingResult(...).is_successful()`.

As a result, this will cause incorrect test reporting, as well as [redundant sequences generated](https://github.com/Yelp/fuzz-lightyear/blob/master/fuzz_lightyear/generator.py#L83).

I'll cut a PR out to address this.

**Comment by domanchi** [comment]
Closing issue, as fix has been merged.
