### ISSUE TITLE
Setup release flow

### ISSUE THREAD

**Issue by Chandra158** [Yelp/fuzz-lightyear#87]
Hi domanchi, OiCMudkips 👋🏼 

I'm setting the upload workflow for this project and need some token from pypi in order to upload future releases to the `pypi` repo.
Would you please add [`yelplabs`](https://pypi.org/user/yelplabs/) account as **maintainer** for this project in [pypi](https://pypi.org/project/fuzz-lightyear/#data).

**Comment by Chandra158** [comment]
cc: @domanchi @OiCMudkips

**Comment by danielpops** [comment]
> This is done. I am also sure that I and @domanchi don't need to be owners on pypi anymore, so let me know if yelplabs should be the owner.

@OiCMudkips yes, please go ahead and make `yelplabs` the owner for this project in pypi. thanks!

**Comment by danielpops** [comment]
@OiCMudkips gentle ping on this

**Comment by OiCMudkips** [comment]
Done
